version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1102.1
    - 0.1102.10
    - 0.1102.2
    - 0.1102.3
    - 0.1102.4
    - 0.1102.5
    - 0.1102.6
    - 0.1102.7
    - 0.1102.8
    - 0.1102.9
    - 0.800.3
  - dependency-name: rxjs
    versions:
    - 6.6.3
    - 6.6.6
    - 6.6.7
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: jasmine-core
    versions:
    - 3.6.0
    - 3.7.0
  - dependency-name: zone.js
    versions:
    - 0.8.29
